<a href="https://colab.research.google.com/github/rambod/ML-Playbook/blob/main/00_pytorch_fundemental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checking GPU



In [48]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Imports

In [49]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


# Introcducing to Tnesor
Creating tensor

In [50]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [51]:
scalar.ndim

0

In [52]:
scalar.item()

7

In [53]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [54]:
vector.ndim

1

In [55]:
vector.shape

torch.Size([2])

In [56]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [57]:
MATRIX.ndim

2

In [58]:
MATRIX[0]

tensor([7, 8])

In [59]:
MATRIX.shape

torch.Size([2, 2])

In [60]:
from torch.functional import Tensor
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [61]:
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

In [63]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [64]:
TENSOR[0][1]

tensor([3, 6, 9])

# Random Tensor
Why Random Tensors?
Random tensors are importnat the way many neural networks learn is that
they start with tensor full og random numbers and then adjust those random numbers
to better reperesnt the data
```
Satrt With Random numbers -> look at the data -> update random numbers -> look at data -> update random numbers
```
Torch Random tensor docs - https://pytorch.org/docs/stable/generated/torch.rand.html

In [65]:
# Create a random tensor of size or shape (3,4)
random_tensor = torch.rand(1,10,10,10)
random_tensor

tensor([[[[0.8237, 0.2346, 0.1765, 0.1373, 0.0344, 0.5404, 0.5254, 0.1484,
           0.1345, 0.5929],
          [0.0642, 0.2908, 0.5709, 0.1696, 0.8408, 0.5390, 0.8868, 0.8968,
           0.7719, 0.3055],
          [0.1324, 0.1686, 0.9543, 0.5991, 0.0287, 0.9179, 0.4877, 0.7694,
           0.0312, 0.8531],
          [0.7249, 0.4041, 0.8073, 0.2390, 0.8141, 0.7810, 0.2621, 0.7695,
           0.7368, 0.7149],
          [0.8022, 0.3812, 0.5838, 0.6746, 0.2598, 0.7139, 0.7975, 0.8731,
           0.2532, 0.6769],
          [0.5165, 0.8735, 0.4872, 0.7742, 0.1189, 0.3625, 0.6609, 0.3210,
           0.7840, 0.2105],
          [0.0484, 0.7796, 0.5589, 0.1638, 0.9444, 0.2705, 0.8657, 0.6063,
           0.8037, 0.8564],
          [0.8622, 0.7387, 0.1207, 0.7051, 0.0942, 0.1194, 0.9349, 0.7467,
           0.7260, 0.7121],
          [0.8355, 0.6826, 0.7551, 0.6045, 0.9637, 0.1544, 0.3487, 0.5260,
           0.9089, 0.9035],
          [0.6319, 0.3027, 0.3995, 0.9316, 0.6798, 0.9732, 0.7408, 0.5418

In [66]:
random_tensor.ndim

4

In [67]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [68]:
torch.rand(size=(3,3))

tensor([[0.5036, 0.3018, 0.1785],
        [0.2673, 0.2640, 0.2134],
        [0.2382, 0.9327, 0.2952]])

# Zeros and Ones

In [69]:
#Create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [70]:
# Create a tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tenors-like
docs -> https://pytorch.org/docs/stable/generated/torch.arange.html

In [72]:
# Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
torch_aranage = torch.arange(start=0, end = 100, step = 12)
torch_aranage

tensor([ 0, 12, 24, 36, 48, 60, 72, 84, 96])

In [74]:
#Creating tesors like
ten_zeros = torch.zeros_like(input=torch_aranage)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

doc -> https://pytorch.org/docs/stable/tensors.html
** Note :** Tensor datatype is one the 3 big issues or erors youll run into with oytirch
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device


In [75]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type is the tensor ( eg. 32 bit , 16 bit , 64 bit)
                               device="cpu", # What device is you tensor it can be CPU or GPU ("cuda")
                               requires_grad=False # wheter or not to track gradients with this tensor opreations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [76]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [77]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [78]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [79]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])



---


# Getting information from tensroes (Tensor Attribute)

1. Tensor not right datatype - to  get datatype from a tensor ```tensor.dtype```
2. Tensor not right shape - to get shappe from a atensor ```tensor.shape```
3. Tensor not on the right device - to get device from a tensor ```tensor.device```


In [80]:
#Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7925, 0.9143, 0.6157, 0.2126],
        [0.8377, 0.1448, 0.7234, 0.5995],
        [0.3749, 0.6193, 0.7446, 0.1342]])

In [81]:
#Find out detail about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.7925, 0.9143, 0.6157, 0.2126],
        [0.8377, 0.1448, 0.7234, 0.5995],
        [0.3749, 0.6193, 0.7446, 0.1342]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


# Mainpulating Tensor ( tensor operations )

Tensor operations include:


* Addition
* Subtraction
* Mulitipication
* Division
* Matrix Multipicaiton



In [82]:
#Create tensor
tensorX = torch.tensor([1,2,3])
tensorX = tensorX + 10
tensorX

tensor([11, 12, 13])

In [83]:
tensorX = tensorX * 10
tensorX

tensor([110, 120, 130])

In [84]:
tensorX = tensorX - 10
tensorX

tensor([100, 110, 120])

In [85]:
tensorX = tensorX.mul(2)
tensorX

tensor([200, 220, 240])

In [86]:
tensor = tensorX

# Matrix Multipication
There is 2 way of multipication for matrix in nureal network and deep learning:
1. Element-wise multipication
2. Matrix multipication ( dot prodct )
More information -> https://www.mathsisfun.com/algebra/matrix-multiplying.html
Intarctive matrix multipication -> http://matrixmultiplication.xyz/

There are two main rules that performing matrix multipication needs to satisfy:
1. The **inner dimentions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shaoe of the **outer dimensions**:
* `(2, 3) @ (3,2)` -> `(2,2)`
* `(3, 2) @ (2,3)` -> `(3,3)`

In [87]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.7950, 0.7002, 0.3473],
        [0.3297, 0.5962, 0.1076],
        [0.7165, 0.6121, 0.3153]])

In [88]:
# Element wise multipication
#print(tensor, "*" , tensor)
#print(f"Equals {tensor * tensor}")

In [89]:
torch.matmul(tensor, tensor)

tensor(146000)

In [90]:
tensor

tensor([200, 220, 240])

In [91]:
# Matrix multipication nby hand
1*1 + 2*2 + 3*3

14

In [92]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(146000)
CPU times: user 1.22 ms, sys: 33 µs, total: 1.26 ms
Wall time: 1.28 ms


In [93]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 75 µs, sys: 11 µs, total: 86 µs
Wall time: 90.4 µs


tensor(146000)

# One of the most common errors in deep learning: Shape errors

In [94]:
#Shapes for matrix multpication
# tensor_A = torch.tensor([[1,2],
#                          [3,4],
#                          [5,6]])
# tensor_B = torch.tensor([[7,10],
#                          [8,11],
#                          [9,12]])
# torch.matmul(tensor_A,tensor_B)

In [95]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues , we can manipulate the shape of the one of our tensor using **transpose**

A **transpose** switches the axes or dimenstion of given tensor.

In [96]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [97]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [98]:
# the matrix multipication operation works when tensor_B is tranposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimention must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T) # mm is same s matmul
print(output)
print(f"\n Output Shape : {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimention must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output Shape : torch.Size([3, 3])


# Findning the min , max , sum , etc (tensor aggregation)

In [99]:
# Create a tensor
x = torch.arange(0,100, 10,dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [100]:
torch.min(x) ,x.min()

(tensor(0.), tensor(0.))

In [101]:
#find max
x.max()

tensor(90.)

In [102]:
# find mean
#torch.mean(x.type(torch.float32))
torch.mean(x)

tensor(45.)

In [103]:
#find sum
torch.sum(x)

tensor(450.)

# Finding the posional min and max

In [104]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [105]:
x[0]

tensor(0.)

In [106]:
#Find the position tensor that he the minimum alue with argim() -> returns index position of that min value
x.argmin()

tensor(0)

In [107]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

# Reshaping stacking , squeezing and unsqueezing tensor

* Reshaping - reshapes an input tensor to defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - Comibine multiple tensors on top of each other -> https://pytorch.org/docs/stable/generated/torch.stack.html
* squeez - removes all `1` dimensions from tensor
* Unsqueeze - add a `1` dimenstion to a target tensor
Permute - return a view of the input with dimention permuted (swapped) in a certain way


In [108]:
# Lets create a tensor
import torch
y = torch.arange(1.,10.)
y , y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [109]:
y_reshaped = y.reshape(1,9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [110]:
y_reshaped2 = y.reshape(9,1)
y_reshaped2

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [111]:
y_reshaped3 = y.reshape(3,3)
y_reshaped3


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [126]:
# lets create new tensor
z = torch.arange(1,10)
z, z.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [127]:
z_reshaped1 = z.reshape(1,9)
z_reshaped1

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [128]:
z_reshaped1 = z.reshape(1,9)
z_reshaped1, z_reshaped1.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [129]:
# Change the view
h = z.view(1,9)
h , h.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [130]:
# changing h is changes z ( becuase a view of tensor shares the same memory as the original)
h[:, 0] = 5
h, z

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [131]:
z

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
#stack tensors on top of each other
z_stacked = torch.stack([z,z,z,z],dim = 1)
z_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [133]:
z.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
z_reshaped1

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [135]:
z_reshaped1.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
z_reshaped1.unsqueeze(dim=1)

tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [137]:
print(f"Previus tensor: {z_reshaped1}")
print(f"Previes shape: {z_reshaped1.shape}")

#Remove Extra Dimentions from z_reshaped
z_squeezed = z_reshaped1.squeeze()
print(f"\nNew tensor: {z_squeezed}")
print(f"New shape: {z_squeezed.shape}")

Previus tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previes shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [141]:
# torch.unsqueeze() - Adds a single dimension to a target tensor at a specific dim(dimention)
print(f"previues target: {z_squeezed}")
print(f"Previuues Shape: {z_squeezed.shape}")

# Add an extra dimention with unsqeeze
z_unsqueezed = z_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {z_unsqueezed}")
print(f"New Shape: {z_unsqueezed.shape}")

previues target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previuues Shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New Shape: torch.Size([1, 9])


In [142]:
# torch.permute - rearaanges the dimentsion of target tensor  in order
x_original = torch.rand(size=(224,224,3)) #[height , width , color_channel]
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 , 1) # shifts axis 0->1 , 1->2 , 2->0

print(f"previes shape : {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[ color_channale , height , width]


previes shape : torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [145]:
x_original[0,0,0]

tensor(0.1868)

# Indexing (Selecting data from Tensor)
Indexing with PyTorch is similar to indexing with Numpy


In [147]:
#Create Tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [148]:
# lets index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [150]:
# lets index on the middle brracket (dim=1)
x[0][0] , x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [153]:
#;ets index on the most inner bracket
x[0][0][0]

tensor(1)

In [154]:
x[0,2,2]

tensor(9)

In [155]:
# You can use also ":" to sellect all of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [156]:
# Get all values of the 0th and 1st dimention but only index 1 of 2nd dimmention
x[:,:,1]

tensor([[2, 5, 8]])

In [157]:
# get all values of the 0 dimention but only the 1 index value of 1st and 2nd dimention
x[:,1,1]

tensor([5])

In [158]:
# Get index 0 of 0h 1st dimention and all values of the 2nd dimention
x[0,0,:]

tensor([1, 2, 3])

In [159]:
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [161]:
# index on x to return 9
# index on x to return 3,6,9
x[0,2,2] , x[:,:,2]

(tensor(9), tensor([[3, 6, 9]]))

# Pytorch tensors & Numpy
Numpy is a popular scientfic python numerical computing library
And because of this, pytorch has functionality to intract with it
* Data in numpy , want in pytorch tensor -> ` torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [5]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # Warrining : when converting from numpy to pytorch , pytoch reflect defualt dtype of float64 unless speceffied otherwise
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype

dtype('float64')

In [4]:
torch.arange(1.0,8.0).dtype

torch.float32

In [6]:
# Change the value of array , what will do this do to `tensor`?
array = array +1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [7]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [8]:
# Change the tensor , what happens to `numpy_tensor`?
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproduciblity ( trying to take random out of random )

In short how a nural network learns:
`start with random numbers -> tensor opration -> update random numbers to try and make them better representation of the data -> agian -> again -> again...`

To reduce randomness in nural networks and Pytorch comes the concept of **random Seed**

Essentialy what the random seed does is "flavour" the randomness.

docs -> https://pytorch.org/docs/stable/notes/randomness.html

In [9]:
torch.rand(3,3)

tensor([[0.4708, 0.8117, 0.8195],
        [0.4768, 0.1870, 0.6160],
        [0.6490, 0.2963, 0.2408]])

In [10]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0150, 0.0143, 0.8559, 0.4124],
        [0.1523, 0.0375, 0.9117, 0.0638],
        [0.2128, 0.3508, 0.5137, 0.7096]])
tensor([[0.9951, 0.1938, 0.7128, 0.2211],
        [0.8905, 0.1630, 0.6509, 0.8525],
        [0.0197, 0.0621, 0.7396, 0.4543]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [18]:
# Lets make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and Pytorch objects on the GPUs ( and making faster computations )


## Getting Gpu run and setup
1. Easiest - Use google colab for a free GPU (options to upgrade as well)
2. Use your own GPU
3. Use cloud computing
docs-> https://pytorch.org/docs/stable/notes/cuda.html

In [1]:
!nvidia-smi

Sun Jul 30 10:03:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for Gpu Access with pytoch

In [2]:
# Check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()


1

### 3. putting tensors ( and models ) on Gpu

In [5]:
#create a tensor ( defualt is on CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if availbale)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [9]:
# if tensor is on GPU , cant transform it to Numpy
# tensor_on_gpu.numpy()

In [10]:
# to fix the GPU with nupy issue , we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Exercies & Extra curriculium
check the site -> https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises